name: Update Translations

on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight UTC
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Cache Node Modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Get textdomain
      id: package_info
      run: |
        TEXT_DOMAIN=$(jq -r '.name' package.json)
        echo "TEXT_DOMAIN=$TEXT_DOMAIN" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        npm install grunt grunt-glotpress grunt-cli

    - name: Download Translations
      run: |
        npx grunt glotpress_download \
                  --domainPath=languages \
                  --url=https://translate.cocartapi.com \
                  --slug=${{ env.TEXT_DOMAIN }} \
                  --textdomain=${{ env.TEXT_DOMAIN }}

    - name: Commit Changes
      run: |
        git config user.name "CoCart Translations Bot"
        git config user.email "bot@cocartapi.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add languages/
          git commit -m "Updated translations from GlotPress"
        else
          echo "No changes detected. Skipping commit."
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update translations from GlotPress"
        branch: update-translations
        title: "Update translations from GlotPress"
        body: |
          This PR updates the translations from [GlotPress](https://translate.cocartapi.com/).
        labels: "translations, automation"
